# Generated by Django 5.1.6 on 2025-02-28 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=330)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=366)),
                ('email', models.EmailField(max_length=366)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toDo', models.IntegerField()),
                ('done', models.IntegerField()),
                ('urgent', models.IntegerField()),
                ('tasksInBoard', models.IntegerField()),
                ('tasksInProgress', models.IntegerField()),
                ('awaitingFeedback', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=366)),
                ('date', models.DateField()),
                ('priority', models.CharField(max_length=366)),
                ('subtasks', models.JSONField(null=True)),
                ('status', models.CharField(max_length=366)),
                ('assignedTo', models.ManyToManyField(to='join.contact')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='join.category')),
            ],
        ),
    ]
