# Generated by Django 5.1.6 on 2025-03-01 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(default='', max_length=366),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignedTo',
            field=models.ManyToManyField(related_name='contact', to='join.contact'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='join.category'),
        ),
    ]
