# Generated by Django 5.1.6 on 2025-03-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_contact_color_alter_task_assignedto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finishedSubtasks',
            field=models.JSONField(null=True),
        ),
    ]
