# Generated by Django 5.1.6 on 2025-03-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_task_finishedsubtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finishedSubtasks',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
