# Generated by Django 5.1.6 on 2025-04-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_alter_task_finishedsubtasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='join.category'),
        ),
    ]
